//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNextPrint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNextPrint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Configuration variables. These must be set per the instructions in the local README file.
        ///$infFileName = &quot;{{VAR_INFFILENAME}}&quot;
        ///$driverName = &quot;{{VAR_DRIVERNAME}}&quot;
        ///$printerDisplayName = &quot;{{VAR_PRINTERNAME}}&quot;
        ///$printerAddress = &quot;{{VAR_PRINTERADDRESS}}&quot;
        ///$duplexingMode = {{VAR_DUPLEXINGMODE}}
        ///$isColor = {{VAR_COLOR}}
        ///$isCollate = {{VAR_COLLATE}}
        ///
        ///# --- Script start. You shouldn&apos;t need to change anything below this line during configuration. ---
        ///
        ///$logPath = &quot;$env:TEMP\ClickNext\logs\$printerDisplayName.log&quot;
        ///func [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallPrinterDriver {
            get {
                return ResourceManager.GetString("InstallPrinterDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Configuration variables. These must be set per the instructions in the local README file.
        ///$printerDisplayName = &quot;{{VAR_PRINTERNAME}}&quot;
        ///
        ///# --- Script start. You shouldn&apos;t need to change anything below this line during configuration. ---
        ///
        ///$logPath = &quot;$env:TEMP\ClickNext\logs\$printerDisplayName.log&quot;
        ///function Write-ClickNextLog {
        ///    param ([string]$message)
        ///    if (!(Test-Path $logPath)) {
        ///        New-Item -Path $logPath -ItemType File -Force
        ///    }
        ///    $timeStamp = Get-Date -UFormat &quot;%Y-%m-%d %T&quot;
        ///    $logLin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UninstallPrinterDriver {
            get {
                return ResourceManager.GetString("UninstallPrinterDriver", resourceCulture);
            }
        }
    }
}
